"""
Unit tests for ProjectAssistant (Phase 6 & 7).
Validates grounded project summaries, remediation plans, onboarding guides,
deep finding explanations, local/mock mode switching, and citations.
"""

from __future__ import annotations

import pytest
from pathlib import Path

from svant.core.ai.mock import MockAIProvider
from svant.core.assistant import ProjectAssistant
from svant.core.intelligence.models import FindingCategory, FindingSeverity, PriorityTier
from svant.db.connection import get_db
from svant.db.repository import Repository


@pytest.fixture
def test_setup(tmp_path: Path):
    db_path = tmp_path / "test_assistant.db"
    db = get_db(str(db_path))
    repo = Repository(db)

    # Create tracked project
    proj = repo.create_project(name="CoreGateway", root_path=str(tmp_path / "gateway"))
    proj_id = proj["id"]

    # Register files
    f1 = repo.upsert_file(
        project_id=proj_id,
        path=str(tmp_path / "gateway" / "main.py"),
        relative_path="main.py",
        filename="main.py",
        extension=".py",
        category="source",
        size_bytes=500,
        modified_time="2026-10-07T12:00:00",
    )
    repo.upsert_extraction(
        file_id=f1["id"],
        project_id=proj_id,
        content_text="from fastapi import FastAPI\napp = FastAPI()\n",
        char_count=45,
        status="completed",
    )

    f2 = repo.upsert_file(
        project_id=proj_id,
        path=str(tmp_path / "gateway" / "README.md"),
        relative_path="README.md",
        filename="README.md",
        extension=".md",
        category="document",
        size_bytes=350,
        modified_time="2026-10-07T12:00:00",
    )
    repo.upsert_extraction(
        file_id=f2["id"],
        project_id=proj_id,
        content_text="# CoreGateway\nHigh performance API Gateway with OAuth.\nRun: uvicorn main:app\n",
        char_count=85,
        status="completed",
    )

    # Set project health
    repo.upsert_project_health(proj_id, {
        "overall_score": 78,
        "grade": "C",
        "summary": "Moderate health with 1 critical security exposure.",
        "critical_count": 1,
        "high_count": 1,
        "medium_count": 2,
    })

    # Add findings
    repo.upsert_findings(proj_id, [
        {
            "id": "f-crit-sec",
            "project_id": proj_id,
            "category": FindingCategory.SECURITY.value,
            "severity": FindingSeverity.CRITICAL.value,
            "priority_tier": PriorityTier.FIX_FIRST.value,
            "title": "Hardcoded JWT Secret",
            "description": "JWT signature key hardcoded in main.py",
            "recommendation": "Load key from environment variable JWT_SECRET",
            "relative_path": "main.py",
            "location": "Line 12",
            "evidence": "JWT_SECRET = 'secret123'",
            "confidence": 1.0,
            "fingerprint": f"{proj_id}:security:jwt:main.py",
            "status": "open",
        },
        {
            "id": "f-high-qual",
            "project_id": proj_id,
            "category": FindingCategory.QUALITY.value,
            "severity": FindingSeverity.HIGH.value,
            "priority_tier": PriorityTier.SHOULD_FIX.value,
            "title": "Monolithic Router Function",
            "description": "Route handler exceeds 200 lines",
            "recommendation": "Decompose into smaller service handlers",
            "relative_path": "main.py",
            "location": "Lines 45-245",
            "evidence": "def handle_everything():",
            "confidence": 0.9,
            "fingerprint": f"{proj_id}:quality:monolith:main.py",
            "status": "open",
        },
    ])

    return {"repo": repo, "project_id": proj_id, "file_id": f1["id"]}


def test_summarize_project_local_mode(test_setup):
    repo = test_setup["repo"]
    proj_id = test_setup["project_id"]

    assistant = ProjectAssistant(repo=repo)
    res = assistant.summarize_project(proj_id)

    assert res["action"] == "summarize"
    assert res["provider"] == "local"
    assert "Executive Project Summary: CoreGateway" in res["content"]
    assert "Purpose & Technology" in res["content"]
    assert "Architecture & Structure" in res["content"]
    assert "78/100 (Grade C)" in res["content"]
    assert "Hardcoded JWT Secret" in res["content"]
    assert len(res["sources"]) > 0


def test_summarize_project_mock_provider(test_setup):
    repo = test_setup["repo"]
    proj_id = test_setup["project_id"]

    mock_provider = MockAIProvider(custom_response="Grounded executive summary generated by Mock Provider.")
    assistant = ProjectAssistant(repo=repo, ai_provider=mock_provider)

    res = assistant.summarize_project(proj_id, provider_name="mock")
    assert res["provider"] == "mock"
    assert res["content"] == "Grounded executive summary generated by Mock Provider."
    assert len(mock_provider.call_history) == 1
    # Verify mock provider received the evidence
    assert "CoreGateway" in mock_provider.call_history[0]["context"]
    assert "Hardcoded JWT Secret" in mock_provider.call_history[0]["context"]


def test_create_improvement_plan(test_setup):
    repo = test_setup["repo"]
    proj_id = test_setup["project_id"]

    assistant = ProjectAssistant(repo=repo)
    res = assistant.create_improvement_plan(proj_id)

    assert res["action"] == "plan"
    assert res["provider"] == "local"
    content = res["content"]
    assert "Phased Remediation Plan" in content
    assert "Phase 1: Immediate Blockers & Security (Fix First)" in content
    assert "Hardcoded JWT Secret" in content
    assert "Phase 2: Quality & Architecture (Should Fix)" in content
    assert "Monolithic Router Function" in content
    assert len(res["sources"]) >= 2


def test_explain_finding_detailed_breakdown(test_setup):
    repo = test_setup["repo"]
    proj_id = test_setup["project_id"]

    assistant = ProjectAssistant(repo=repo)
    res = assistant.explain_finding(proj_id, "f-crit-sec")

    assert res["action"] == "explain_finding"
    assert res["provider"] == "local"
    content = res["content"]
    assert "WHAT Was Detected?" in content
    assert "WHERE Is the Issue Located?" in content
    assert "WHY Does It Matter?" in content
    assert "RISK If Ignored" in content
    assert "HOW TO FIX" in content
    assert "EVIDENCE (Redacted Locally)" in content
    assert "PRIORITY RATIONALE" in content
    assert len(res["sources"]) == 1
    assert res["sources"][0]["relative_path"] == "main.py"


def test_onboarding_guide_grounding(test_setup):
    repo = test_setup["repo"]
    proj_id = test_setup["project_id"]

    assistant = ProjectAssistant(repo=repo)
    res = assistant.create_onboarding_guide(proj_id)

    assert res["action"] == "onboarding"
    assert res["provider"] == "local"
    content = res["content"]
    assert "Contributor Onboarding Guide: CoreGateway" in content
    assert "main.py" in content
    assert "README.md" in content
    assert "Suggested First Steps for Contributors" in content
    assert len(res["sources"]) >= 1


def test_get_structured_summary(test_setup):
    repo = test_setup["repo"]
    proj_id = test_setup["project_id"]

    assistant = ProjectAssistant(repo=repo)
    data = assistant.get_structured_summary(proj_id)

    assert data["project_id"] == proj_id
    assert data["name"] == "CoreGateway"
    assert data["total_files"] == 2
    assert "main.py" in data["entry_points"]
    assert data["health_score"] == 78
    assert data["grade"] == "C"
